# Generated by Django 3.0.6 on 2020-12-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
